export enum ScreenNames {
    MainHome = "Home",
    MainWorkoutPlayer = "WorkoutPlayer",
    MainWorkoutPlayerEnd = "WorkoutPlayerEnd",
    MainWorkoutAddEdit = "WorkoutAddEdit",
    MainExerciseAddEdit = "ExerciseAddEdit",
    MainGroupAddEdit = "GroupAddEdit",
    MainWarningBack = "WarningBack",
    MainWorkoutNotifications = "WorkoutNotifications",
    MainWorkoutNotificationAddEdit = "NotificationAddEdit",
    MainStatistic = "Statistic",
    MainGoal = "Goal",
    MainDialog = "Dialog",
    SettingsTest = "SettingsTest",
    SettingsHome = "SettingsHome",
    SettingsLanguage = "SettingsLanguage",
    SettingsExport = "SettingsExport",
}